### ISSUE TITLE
Missing last section

### ISSUE THREAD

**Issue by dag7dev** [LBreda/lbreda_com#1]
![image](https://user-images.githubusercontent.com/44711271/134696032-f6fdae74-09c9-4c08-8985-43f394361b48.png)
As shown in screenshot, title in last section is missing. Furthermore, I have no idea what a ASC file is :D
(I think it is something related to your signature but I am not sure).

Anyway, great job!

**Comment by LBreda** [comment]
Thank you, I solved it some days ago (I missed the notification). Yep, it is my public GPG key.
